[package]
name = "AVALANCHE"
version = "0.1.0"
edition = "2021"
license = "GPLv3"

[[bin]]
name = "avalanche"
path = "src/main.rs"

[dependencies]
cursive = "0.21.1"
dirs = "6.0.0"
ron = "0.10.1"
serde = { version = "1", features = ["derive"] }
