[package]
name = "R01_AVALANCHE"
version = "0.1.0"
edition = "2021"
license = "GPLv3"

[[bin]]
name = "avalanche"
path = "src/main.rs"

[dependencies]
cursive = "0.21.1"
dirs = "5.0.1"
ron = "0.8.1"
serde = { version = "1", features = ["derive"] }
